name: 'roboware CI'
description: 'CI for roboware'
author: "Taiga Takano"
branding:
  icon: "activity"
  color: "gray-dark"

inputs:
  apt-url-packages:
    description: "APT packages to be installed as dependencies."
    required: false
  external-repos:
    description: "External repositories to be included as dependencies."
    required: false

runs:
  using: 'docker'
  image: 'dind/Dockerfile'
  args:
    - '${{ inputs.apt-url-packages }}'
