on:
  schedule:
    - cron: '22 9 * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

name: Docker Build and Push

jobs:
  publish_docker_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker Image
        run: |
          docker build --tag ghcr.io/hakoroboken/rwci:latest \
          --tag ghcr.io/hakoroboken/rwci:$(echo $GITHUB_SHA | head -c7) \
          ./base_image
      - name: Push Docker Image
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          docker push ghcr.io/hakoroboken/rwci:latest
          docker push ghcr.io/hakoroboken/rwci:$(echo $GITHUB_SHA | head -c7)